"""traefik - emit role-named Traefik file-provider routers for a module.

Routers are named for the ROLE they serve (mcp / hacker / collector), never for the module, because
Traefik names are a flat global namespace and exactly one module is deployed at a time. One generated
file therefore serves whichever module is currently up, and `grep mr-` over the dynamic config shows
everything the lab exposes.

Static: it reads the module manifest and the environment, and needs no VM and no Docker.
"""
from __future__ import annotations

import os

import catalog as cat

# role -> (public-hostname variable, published-port variable). Kept beside ROLE_VOCAB in check.py:
# adding a role is a deliberate edit in both places, which is the point of a closed vocabulary.
ROLE_VARS = {
    "mcp": ("PUBLIC_MCP_HOST", "MCP_PORT"),
    "hacker": ("PUBLIC_HACKER_HOST", "WEB_PORT"),
    "collector": ("PUBLIC_COLLECTOR_HOST", "COLLECTOR_PORT"),
    "rebind": ("LAB_REBIND_HOST", "REBIND_HTTP_PORT"),
}


def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default)


def cmd_traefik(args) -> int:
    m = cat.require(args.module)
    if not (m.get("topology") or {}).get("traefik", False):
        print(f"REFUSING: module {m['id']} ({m['slug']}) declares topology.traefik: false.")
        print("A reverse proxy cannot express this attack: the flip has to happen in the DNS answer,")
        print("not in a proxy backend. Publish the ports directly and move the record instead.")
        return 2

    prefix = _env("TRAEFIK_ROUTER_PREFIX", "mr")
    entrypoint = _env("TRAEFIK_ENTRYPOINT", "websecure")
    resolver = _env("TRAEFIK_CERTRESOLVER", "")
    vm_ip = _env("LAB_VM_IP", "")
    attacker_ip = _env("ATTACKER_HOST_IP", vm_ip)

    if not vm_ip:
        print("# WARNING: LAB_VM_IP is unset, so backend URLs below are placeholders.", flush=True)

    routers: list[str] = []
    services: list[str] = []
    for role in cat.roles(m):
        name = str(role.get("role"))
        if name not in ROLE_VARS:
            print(f"# skipping unknown role `{name}` (no host/port variables defined)")
            continue
        host_var, port_var = ROLE_VARS[name]
        host = _env(host_var)
        port = _env(port_var, str(role.get("port", 80)))
        if not host:
            print(f"# skipping role `{name}`: {host_var} is unset")
            continue
        ip = attacker_ip if role.get("side") == "attacker" else vm_ip
        rname = f"{prefix}-{name}"
        tls = f"\n      tls:\n        certResolver: {resolver}" if resolver else ""
        routers.append(
            f"    {rname}:\n"
            f"      rule: \"Host(`{host}`)\"\n"
            f"      entryPoints: [{entrypoint}]\n"
            f"      service: {rname}{tls}"
        )
        services.append(
            f"    {rname}:\n"
            f"      loadBalancer:\n"
            f"        servers:\n"
            f"          - url: \"http://{ip or '<LAB_VM_IP>'}:{port}\""
        )

    if not routers:
        print("# no routable roles: set the PUBLIC_* host variables in .env first (see .env.example)")
        return 2

    print(f"# Meridian Range - Traefik dynamic config for module {m['id']} ({m['slug']}).")
    print("# Generated by `range traefik`; role-named, so it serves whichever module is deployed.")
    print("# Drop into your Traefik file/dynamic provider directory. Isolated lab LAN only.")
    print("http:")
    print("  routers:")
    print("\n".join(routers))
    print("  services:")
    print("\n".join(services))
    return 0
